---
- name: Ensure dependencies are present
  become: true
  apt:
    name:
      - ca-certificates
      - apt-transport-https
      - gconf2
      - libasound2
      - libgtk2.0-0
      - libxss1

- name: Ensure repo key is present
  become: true
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc

- name: Ensure repo is present
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    filename: vscode

- name: Ensure package is present
  become: true
  apt:
    name:
      - vscode
    update_cache: true

- name: Ensures config dir exists
  file:
    path: "{{ ansible_env.HOME }}/.config/Code/User"
    state: directory
    recurse: yes

- name: Ensure config is present
  copy:
    src: settings.json
    dest: "{{ ansible_env.HOME }}/.config/Code/User/settings.json"
    mode: 0644
